### ISSUE TITLE
Error: json: cannot unmarshal object into Go struct field SoftForks.softforks of type []*btcjson.SoftForkDescription

### ISSUE THREAD

**Issue by stefansundin** [OdyseeTeam/chainquery#167]
Hello.

I am trying to get lbrycrd and chainquery to work. I have started my own repo with a docker-compose setup: https://github.com/stefansundin/lbry-dev-environment

I am using the docker images `lbry/lbrycrd:v0.17.3.2` and `lbry/chainquery:v2.4.0`. I have tried a few different combinations without luck.

I am encountering an error but I can't figure out how to get past it.

```
chainquery_1  | [INFO]: Found a copy of chainqueryconfig.toml in /etc/lbry
chainquery_1  | time="2021-04-02T01:09:25Z" level=info msg="SETTINGS: debug mode turned on"
chainquery_1  | time="2021-04-02T01:09:25Z" level=info msg="Applied 0 migrations"
chainquery_1  | time="2021-04-02T01:09:25Z" level=panic msg="Initializing LBRYcrd Client: json: cannot unmarshal object into Go struct field SoftForks.softforks of type []*btcjson.SoftForkDescription"
chainquery_1  | panic: (*logrus.Entry) (0xd85a80,0xc000134070)
chainquery_1  |
chainquery_1  | goroutine 1 [running]:
chainquery_1  | github.com/sirupsen/logrus.Entry.log(0xc0000fd960, 0xc0002c6510, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
chainquery_1  | 	/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2db
chainquery_1  | github.com/sirupsen/logrus.(*Entry).Log(0xc000134000, 0xc000000000, 0xc000141bd8, 0x2, 0x2)
chainquery_1  | 	/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xeb
chainquery_1  | github.com/sirupsen/logrus.(*Logger).Log(0xc0000fd960, 0x0, 0xc000141bd8, 0x2, 0x2)
chainquery_1  | 	/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x7d
chainquery_1  | github.com/sirupsen/logrus.(*Logger).Panic(...)
chainquery_1  | 	/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:233
chainquery_1  | github.com/sirupsen/logrus.Panic(...)
chainquery_1  | 	/home/travis/gopath/pkg/mod/github.com/sirupsen/logrus@v1.4.2/exported.go:129
chainquery_1  | github.com/lbryio/chainquery/lbrycrd.Init(0xc000141c88)
chainquery_1  | 	/home/travis/gopath/src/github.com/lbryio/chainquery/lbrycrd/client.go:30 +0xe0
chainquery_1  | github.com/lbryio/chainquery/cmd.glob..func8(0x1595e80, 0xc00000c2e0, 0x0, 0x2)
chainquery_1  | 	/home/travis/gopath/src/github.com/lbryio/chainquery/cmd/serve.go:42 +0x20c
chainquery_1  | github.com/spf13/cobra.(*Command).execute(0x1595e80, 0xc00000c280, 0x2, 0x2, 0x1595e80, 0xc00000c280)
chainquery_1  | 	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
chainquery_1  | github.com/spf13/cobra.(*Command).ExecuteC(0x1596f20, 0x43d3fa, 0x154ff40, 0xc00003a750)
chainquery_1  | 	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
chainquery_1  | github.com/spf13/cobra.(*Command).Execute(...)
chainquery_1  | 	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
chainquery_1  | github.com/lbryio/chainquery/cmd.Execute()
chainquery_1  | 	/home/travis/gopath/src/github.com/lbryio/chainquery/cmd/root.go:47 +0x31
chainquery_1  | main.main()
chainquery_1  | 	/home/travis/gopath/src/github.com/lbryio/chainquery/main.go:13 +0x20
lbry-dev-environment_chainquery_1 exited with code 2
```

The best I could find was this: https://github.com/lightningnetwork/lnd/issues/3412. But since I have tried different version combinations, I am not sure that's the problem.

It would be great if someone could help me. Thank you!

**Comment by tiger5226** [comment]
@stefansundin do you think you could share your docker-compose file that produces this? So I can debug it locally to see what the problem might be.

**Comment by stefansundin** [comment]
@tiger5226 Hi. There's a link to the docker-compose file and chainquery config in the issue description.
